name: Build Go Binary

on:
  push:
    branches:
      - main  # Chạy khi có code mới trên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clone code về runner

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Cài đặt Go phiên bản 1.21

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o myservice  # Build binary cho Linux

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: myservice
          path: myservice

      - name: Copy binary to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa myservice ec2-user@ec2-3-25-117-47.ap-southeast-2.compute.amazonaws.com:/home/ec2-user/go-server/myservice
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@ec2-3-25-117-47.ap-southeast-2.compute.amazonaws.com << 'EOF'
          sudo systemctl restart myservice
          sudo systemctl status myservice
          EOF

